### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by kairushinjuu** [nKeee/nKes-Runelite-Plugins#1]
How do we put these into Runelite sorry for the stupid question

**Comment by nKeee** [comment]
I havent compiled a .jar for release, so you'd need to:

1. Use a IDE (I use IntelliJ IDEA) to compile the .jar file
2. Use a modified runelite cheat client **OR** sideload the plugins using runelites devmode (This is what I do)

Step-by-step guides on how to launch the devmode & compile the plugins are available at [RuneLite wiki.](https://github.com/runelite/runelite/wiki/Using-the-client-developer-tools)
